version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gastos_postgres
    restart: always
    environment:
      POSTGRES_USER: gastos_user
      POSTGRES_PASSWORD: gastos_password
      POSTGRES_DB: gastos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
